version: '3'

services: 
    client:
        container_name: prueba
        build: ./front
        image: test
        ports: 
            - "3000:3000"
        volumes: 
            - ./front:/usr/src/app
        stdin_open: true
        tty: true
